"""
TypedDict models for the Creem REST API.

Generated by scripts/generate_models.py from the official OpenAPI spec
(https://docs.creem.io/api-reference/openapi.json). Do not edit by hand.
"""

from __future__ import annotations

from typing import Any, Literal, NotRequired, Required, TypedDict


# --- Enums ---

# The settlement status of the commission. `pending` while on hold, `approved` once cleared and available, `paid` once settled by a payout.
CommissionStatus = Literal['pending', 'approved', 'paid']

# The duration type for the discount.
CouponDurationType = Literal['forever', 'once', 'repeating']

# The type of the field.
CustomFieldRequestType = Literal['text', 'checkbox']

# The type of the field.
CustomFieldType = Literal['text', 'checkbox']

# The type of the discount, either "percentage" or "fixed".
DiscountType = Literal['percentage', 'fixed']

# String representing the environment.
EnvironmentMode = Literal['test', 'prod', 'sandbox']

# The current status of the license key.
LicenseStatus = Literal['inactive', 'active', 'expired', 'disabled']

# Current status of the order.
OrderStatus = Literal['pending', 'paid']

# The type of order. This can specify whether it's a regular purchase, subscription, etc.
OrderType = Literal['recurring', 'onetime']

# Billing period
ProductBillingPeriod = Literal['every-month', 'every-three-months', 'every-six-months', 'every-year', 'every-day', 'once']

# Indicates the billing method for the customer. It can either be a `recurring` billing cycle or a `onetime` payment.
ProductBillingType = Literal['recurring', 'onetime']

# Three-letter uppercase ISO 4217 currency code. Must be one of Creem's supported currencies.
ProductCurrency = Literal['EUR', 'USD']

# The type of the feature: `custom` (private note), `file` (downloadable files), `licenseKey` (license key), or `customerCredits` (customer credit grant).
ProductFeatureType = Literal['custom', 'file', 'licenseKey', 'customerCredits']

# Billing interval. Required when `billing_type` is `recurring`.
ProductRequestBillingPeriod = Literal['once', 'every-day', 'every-month', 'every-three-months', 'every-six-months', 'every-year']

# Billing method for the product: `recurring` subscription or `onetime` payment.
ProductRequestBillingType = Literal['recurring', 'onetime']

# Lifecycle status of the product: `active` or `archived`.
ProductStatus = Literal['active', 'archived']

# Reason for the refund.
RefundReason = Literal['duplicate', 'fraudulent', 'requested_by_customer', 'other']

# Status of the refund. `pending` and `requiresAction` represent non-terminal provider processing states.
RefundStatus = Literal['pending', 'requiresAction', 'succeeded', 'failed', 'canceled']

# The method used for collecting payments for the subscription.
SubscriptionCollectionMethod = Literal['charge_automatically']

# The current status of the subscription.
SubscriptionStatus = Literal['active', 'canceled', 'unpaid', 'paused', 'trialing', 'scheduled_cancel', 'past_due']

# Categorizes the type of product or service for tax purposes. This helps determine the applicable tax rules based on the nature of the item or service.
TaxCategory = Literal['saas', 'digital-goods-service', 'ebooks']

# Specifies the tax calculation mode for the transaction. If set to "inclusive," the tax is included in the price. If set to "exclusive," the tax is added on top of the price.
TaxMode = Literal['inclusive', 'exclusive']

# Status of the transaction.
TransactionStatus = Literal['pending', 'paid', 'refunded', 'partialRefund', 'chargedBack', 'uncollectible', 'declined', 'canceled', 'void']

# The type of transaction. payment(one time payments) and invoice(subscription)
TransactionType = Literal['payment', 'invoice']


# --- Object models ---

class CreditsAccountList(TypedDict):
    object: NotRequired[str]  # Object type
    data: NotRequired[list[CreditsAccount]]  # Array of accounts
    has_more: NotRequired[bool]  # Whether more items exist beyond this page

class CreditsAccount(TypedDict):
    id: NotRequired[str]  # Account ID
    store_id: NotRequired[str]  # Store ID
    customer_id: NotRequired[str]  # Owner ID
    name: NotRequired[str]  # Account name
    unit_label: NotRequired[str]  # Unit label
    status: NotRequired[CreditsAccountStatus]  # Account status
    created_at: NotRequired[str]  # Creation timestamp
    updated_at: NotRequired[str]  # Last update timestamp

# Account status
CreditsAccountStatus = Literal['active', 'frozen', 'closed']

class LicenseActivateParams(TypedDict):
    key: Required[str]  # The license key to activate.
    instance_name: Required[str]  # A label for the new instance to identify it in Creem.

class Affiliate(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # String representing the object's type. Objects of the same type share the same value.
    email: NotRequired[str]  # The email address the affiliate was invited with.
    name: NotRequired[str]  # The display name of the affiliate, if set.
    status: NotRequired[str]  # The affiliate's status within your program, reflecting their membership standing: `active`, `pending` (awaiting approval), `rejected`, `suspended`, or `inactive` (left or removed). Invited-but-not-yet-joined affiliates are not returned by this endpoint.
    referral_code: NotRequired[str]  # The affiliate's unique referral code.
    referral_link: NotRequired[str]  # The affiliate's shareable referral link. Traffic arriving through it is attributed to this affiliate.
    clicks: NotRequired[int]  # Total number of clicks recorded on the affiliate’s links.
    conversions: NotRequired[int]  # Total number of conversions attributed to the affiliate.
    earnings: NotRequired[int]  # Lifetime commission earned by the affiliate, in cents (1000 = $10.00), reported in a single primary currency (see `currency`). Affiliates earning in multiple currencies show only their highest-earning currency here; use the affiliate's commissions endpoint for the full per-currency breakdown.
    currency: NotRequired[str]  # Three-letter ISO currency code, in uppercase, for the `earnings` amount. This is the affiliate's primary (highest-earning) currency; commissions in other currencies are listed individually on the commissions endpoint.

class AffiliateList(TypedDict):
    items: NotRequired[list[Affiliate]]  # List of affiliate items
    pagination: NotRequired[Pagination]  # Pagination details for the list

class CreditsBalance(TypedDict):
    balance: NotRequired[str]  # Current balance as string for bigint safety
    updated_at: NotRequired[str]  # Last update timestamp (present for projected balance)
    as_of: NotRequired[str]  # Point-in-time the balance was computed at (present for at-time queries)

class SubscriptionCancelParams(TypedDict):
    mode: NotRequired[SubscriptionCancelParamsMode]  # The mode of cancellation (immediate or scheduled), default can be configured in the store billing settings.
    onExecute: NotRequired[SubscriptionCancelParamsOnExecute]  # The action to execute when canceling (cancel or pause) when mode is scheduled, ignored when mode is immediate or not provided

# The mode of cancellation (immediate or scheduled), default can be configured in the store billing settings.
SubscriptionCancelParamsMode = Literal['immediate', 'scheduled']

# The action to execute when canceling (cancel or pause) when mode is scheduled, ignored when mode is immediate or not provided
SubscriptionCancelParamsOnExecute = Literal['cancel', 'pause']

class CustomFieldCheckbox(TypedDict):
    label: NotRequired[str]  # The markdown text to display for the checkbox.
    value: NotRequired[bool]  # The value of the checkbox (checked or not).

class CustomFieldCheckboxConfig(TypedDict):
    label: NotRequired[str]  # The markdown text to display for the checkbox.

class Checkout(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # String representing the object's type. Objects of the same type share the same value.
    status: NotRequired[CheckoutStatus]  # Status of the checkout.
    request_id: NotRequired[str]  # Identify and track each checkout request.
    product: NotRequired[str | Product]  # The product associated with the checkout session.
    units: NotRequired[int]  # The number of units for the of the product.
    custom_price: NotRequired[int]  # The per-unit price override (in cents, product currency) this checkout was created with. Only present when the checkout was created with a custom_price. One-time payment products only.
    order: NotRequired[Order]  # The order associated with the checkout session.
    subscription: NotRequired[str | Subscription]  # The subscription associated with the checkout session.
    customer: NotRequired[str | Customer]  # The customer associated with the checkout session.
    custom_fields: NotRequired[list[CustomField]]  # Additional information collected from your customer during the checkout process.
    checkout_url: NotRequired[str]  # The URL to which the customer will be redirected to complete the payment.
    success_url: NotRequired[str]  # The URL to which the user will be redirected after the checkout process is completed.
    license_keys: NotRequired[list[License]]  # License keys issued for the order.
    feature: NotRequired[list[ProductFeature]]  # DEPRECATED: Use `license_keys` instead. Features issued for the order.
    metadata: NotRequired[dict[str, Any]]  # Metadata for the checkout in the form of key-value pairs
    discount: NotRequired[CheckoutDiscount]  # The discount applied to the checkout, if any.

class CheckoutDiscount(TypedDict):
    """The discount applied to the checkout, if any."""
    id: NotRequired[str]
    discountCode: NotRequired[str]
    name: NotRequired[str]
    type: NotRequired[CheckoutDiscountType]
    amount: NotRequired[int]
    duration: NotRequired[CheckoutDiscountDuration]
    durationInMonths: NotRequired[int]

# Status of the checkout.
CheckoutStatus = Literal['pending', 'processing', 'completed', 'expired']

CheckoutDiscountType = Literal['percentage', 'fixed']

CheckoutDiscountDuration = Literal['forever', 'once', 'repeating']

class Commission(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # String representing the object's type. Objects of the same type share the same value.
    affiliate: NotRequired[str]  # The ID of the affiliate this commission belongs to.
    amount: NotRequired[int]  # The commission amount in cents. 1000 = $10.00
    currency: NotRequired[str]  # Three-letter ISO currency code, in uppercase, for the commission amount.
    status: NotRequired[CommissionStatus]
    sale: NotRequired[str]  # The ID of the sale transaction that generated this commission, if available.
    created_at: NotRequired[int]  # Creation date of the commission as a timestamp.

class CommissionList(TypedDict):
    items: NotRequired[list[Commission]]  # List of commission items
    pagination: NotRequired[Pagination]  # Pagination details for the list

class CreditsAccountCreateParams(TypedDict):
    name: NotRequired[str]  # Human-readable name for the account
    customer_id: Required[str]  # The owner ID this account belongs to (e.g. customer ID)
    unit_label: NotRequired[str]  # Label for the unit of currency/credits
    initial_balance: NotRequired[str]  # Seed the account with this many credits on creation

class CheckoutCreateParams(TypedDict):
    request_id: NotRequired[str]  # Identify and track each checkout request.
    product_id: Required[str]  # The ID of the product associated with the checkout session.
    units: NotRequired[int]  # The number of units for the order.
    custom_price: NotRequired[int]  # Override the unit price of the product for this checkout session, in cents (e.g. 1500 = $15.00). The product currency is used, and the amount is per unit: with `units: 3` and `custom_price: 1500` the customer pays 4500. Must be between 100 (one whole unit of the currency) and 99999999. Only supported for one-time payment products. Use this for dynamic pricing models such as pay-what-you-want, donations, or amounts calculated by your application.
    discount_code: NotRequired[str]  # Prefill the checkout session with a discount code.
    customer: NotRequired[CheckoutCustomerParams]  # Customer data for checkout session. This will prefill the customer info on the checkout page.
    custom_fields: NotRequired[list[CustomFieldParams]]  # Collect additional information from your customer using custom fields. Up to 3 fields are supported.
    custom_field: NotRequired[list[CustomFieldParams]]  # DEPRECATED: Use `custom_fields` instead. Collect additional information from your customer using custom fields. Up to 3 fields are supported.
    success_url: NotRequired[str]  # The URL to which the user will be redirected after the checkout process is completed.
    metadata: NotRequired[dict[str, Any]]  # Metadata for the checkout in the form of key-value pairs

class CustomerBillingParams(TypedDict):
    customer_id: Required[str]  # Unique identifier of the customer.

class CustomerCreateParams(TypedDict):
    email: Required[str]  # The email address of the customer.
    name: Required[str]  # The full name of the customer.
    metadata: NotRequired[dict[str, Any]]  # Additional metadata for the customer.

class DiscountCreateParams(TypedDict):
    name: Required[str]  # The name of the discount.
    code: NotRequired[str]  # Optional discount code. If left empty, a code will be generated.
    type: Required[DiscountType]
    amount: NotRequired[int]  # The fixed value for the discount. Only applicable if the type is "fixed".
    currency: NotRequired[str]  # The currency of the discount. Only required if type is "fixed".
    percentage: NotRequired[float]  # The percentage value for the discount. Only applicable if the type is "percentage".
    expiry_date: NotRequired[str]  # The expiry date of the discount.
    max_redemptions: NotRequired[int]  # The maximum number of redemptions for the discount.
    duration: Required[CouponDurationType]
    duration_in_months: NotRequired[int]  # The number of months the discount is valid for. Only applicable if the duration is "repeating" and the product is a subscription.
    applies_to_products: Required[list[str]]  # The list of product IDs to which this discount applies.

class ProductCreateParams(TypedDict):
    name: Required[str]  # Name of the product
    description: Required[str]  # Description of the product
    image_url: NotRequired[str]  # URL of the product image
    image_urls: NotRequired[list[str]]  # Ordered list of product image URLs (max 8). The first entry is the cover image; when provided it takes precedence over image_url.
    price: Required[int]  # The price of the product in cents. Must be 0 (free product) or at least 100 (one whole unit of the currency).
    currency: Required[ProductCurrency]
    billing_type: Required[ProductRequestBillingType]
    billing_period: NotRequired[ProductRequestBillingPeriod]
    tax_mode: NotRequired[TaxMode]
    tax_category: NotRequired[TaxCategory]
    pay_what_you_want: NotRequired[bool]  # Enable pay-what-you-want pricing: the customer chooses the amount at checkout. The `price` field acts as the minimum the customer must pay. Only supported for one-time payment products.
    suggested_price: NotRequired[int]  # Suggested amount in cents, pre-filled at checkout when pay_what_you_want is enabled. Must be greater than or equal to `price` (the minimum). Ignored when pay_what_you_want is disabled.
    default_success_url: NotRequired[str]  # The URL to which the user will be redirected after successfull payment.
    custom_fields: NotRequired[list[CustomFieldParams]]  # Collect additional information from your customer using custom fields during checkout. Up to 3 fields are supported.
    custom_field: NotRequired[list[CustomFieldParams]]  # DEPRECATED: Use `custom_fields` instead. Collect additional information from your customer using custom fields during checkout. Up to 3 fields are supported.
    abandoned_cart_recovery_enabled: NotRequired[bool]  # Enable abandoned cart recovery for this product

class RefundCreateParams(TypedDict):
    transaction_id: Required[str]  # The unique identifier of the transaction to refund in full.

class CreditDebitParams(TypedDict):
    amount: Required[str]  # Amount to credit or debit (string to support large numbers)
    reference: Required[str]  # Your reference ID to link this transaction to an event in your system (e.g. order ID, campaign ID)
    idempotency_key: Required[str]  # Idempotency key to prevent duplicate transactions

class CustomField(TypedDict):
    type: NotRequired[CustomFieldType]
    key: NotRequired[str]  # Unique key for custom field. Must be unique to this field, alphanumeric, and up to 200 characters.
    label: NotRequired[str]  # The label for the field, displayed to the customer, up to 50 characters
    optional: NotRequired[bool]  # Whether the customer is required to complete the field. Defaults to `false`.
    text: NotRequired[CustomFieldText]  # Configuration for text field type.
    checkbox: NotRequired[CustomFieldCheckbox]  # Configuration for checkbox field type.

class CustomFieldParams(TypedDict):
    type: Required[CustomFieldRequestType]
    key: Required[str]  # Unique key for custom field. Must be unique to this field, alphanumeric, and up to 200 characters.
    label: Required[str]  # The label for the field, displayed to the customer, up to 50 characters.
    optional: NotRequired[bool]  # Whether the customer is required to complete the field. Defaults to `false`
    text: NotRequired[CustomFieldTextConfig]  # Configuration for text field type.
    checkbox: NotRequired[CustomFieldCheckboxConfig]  # Configuration for checkbox field type.

class CreditsErrorDetail(TypedDict):
    type: NotRequired[CreditsErrorDetailType]  # Error category
    code: NotRequired[str]  # Machine-readable error code
    message: NotRequired[str]  # Human-readable error message
    param: NotRequired[str]  # The parameter related to the error, if applicable
    request_id: NotRequired[str]  # Unique request identifier for support

# Error category
CreditsErrorDetailType = Literal['invalid_request_error', 'api_error', 'authentication_error', 'rate_limit_error']

class CreditsErrorResponse(TypedDict):
    error: NotRequired[CreditsErrorDetail]  # Error details

class CustomerCreditsFeature(TypedDict):
    amount: NotRequired[str]  # The number of credits to grant. String to preserve BigInt precision.
    unit_label: NotRequired[str]  # Optional label for the credit unit (e.g. "tokens", "credits").

class Customer(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # String representing the object’s type. Objects of the same type share the same value.
    email: NotRequired[str]  # Customer email address.
    name: NotRequired[str]  # Customer name.
    metadata: NotRequired[dict[str, Any]]  # Additional metadata associated with the customer.
    country: NotRequired[str]  # The ISO 3166-1 alpha-2 country code for the customer.
    created_at: NotRequired[str]  # Creation date of the customer
    updated_at: NotRequired[str]  # Last updated date of the customer

class CustomerBillingLinks(TypedDict):
    customer_portal_link: NotRequired[str]  # Customer portal link.

class CustomerList(TypedDict):
    items: NotRequired[list[Customer]]  # List of customer items
    pagination: NotRequired[Pagination]  # Pagination details for the list

class CheckoutCustomerParams(TypedDict):
    id: NotRequired[str]  # Unique identifier of the customer. You may specify only one of these parameters: id or email.
    email: NotRequired[str]  # Customer email address. You may only specify one of these parameters: id, email.

class LicenseDeactivateParams(TypedDict):
    key: Required[str]  # The license key to deactivate.
    instance_id: Required[str]  # Id of the instance to deactivate.

class Discount(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # A string representing the object’s type. Objects of the same type share the same value.
    status: NotRequired[DiscountStatus]  # The status of the discount (e.g., active, inactive).
    name: NotRequired[str]  # The name of the discount.
    code: NotRequired[str]  # The discount code. A unique identifier for the discount.
    type: NotRequired[DiscountType]  # The type of the discount, either "percentage" or "fixed".
    amount: NotRequired[float]  # The amount of the discount. Can be a percentage or a fixed amount.
    currency: NotRequired[str]  # The currency of the discount. Only required if type is "fixed".
    percentage: NotRequired[float]  # The percentage of the discount. Only applicable if type is "percentage".
    expiry_date: NotRequired[str]  # The expiry date of the discount.
    max_redemptions: NotRequired[int]  # The maximum number of redemptions allowed for the discount.
    duration: NotRequired[DiscountDuration]  # The duration type for the discount.
    duration_in_months: NotRequired[int]  # The number of months the discount is valid for. Only applicable if the duration is "repeating" and the product is a subscription.
    applies_to_products: NotRequired[list[str]]  # The list of product IDs to which this discount applies.
    redeem_count: NotRequired[int]  # The number of times this discount has been redeemed.

# The status of the discount (e.g., active, inactive).
DiscountStatus = Literal['deleted', 'active', 'draft', 'expired', 'scheduled']

# The duration type for the discount.
DiscountDuration = Literal['forever', 'once', 'repeating']

class DiscountList(TypedDict):
    items: NotRequired[list[Discount]]  # List of discount items
    pagination: NotRequired[Pagination]  # Pagination details for the list

class Dispute(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # String representing the object's type. Objects of the same type share the same value.
    amount: NotRequired[int]  # The disputed amount in cents. 1000 = $10.00
    currency: NotRequired[str]  # Three-letter ISO currency code, in uppercase. Must be a supported currency.
    transaction: NotRequired[Transaction]  # The transaction associated with the dispute.
    checkout: NotRequired[str | Checkout]  # The checkout associated with the dispute.
    order: NotRequired[str | Order]  # The order associated with the dispute.
    subscription: NotRequired[str | Subscription]  # The subscription associated with the dispute.
    customer: NotRequired[str | Customer]  # The customer associated with the dispute.
    created_at: NotRequired[int]  # Creation date of the dispute as timestamp

class CreditsEntryList(TypedDict):
    object: NotRequired[str]  # Object type
    data: NotRequired[list[CreditsEntry]]  # Array of entries
    has_more: NotRequired[bool]  # Whether more items exist beyond this page

class CreditsEntry(TypedDict):
    id: NotRequired[str]  # Entry ID
    transaction_id: NotRequired[str]  # Transaction ID
    account_id: NotRequired[str]  # Account ID
    side: NotRequired[CreditsEntrySide]  # Debit or credit side
    amount: NotRequired[str]  # Amount as string for bigint safety
    created_at: NotRequired[str]  # Creation timestamp

# Debit or credit side
CreditsEntrySide = Literal['debit', 'credit']

class Feature(TypedDict):
    id: NotRequired[str]  # Unique identifier for the feature.
    type: NotRequired[ProductFeatureType]
    description: NotRequired[str]  # A brief description of the feature.

class FeatureFile(TypedDict):
    id: NotRequired[str]  # Unique identifier for the file.
    file_name: NotRequired[str]  # The name of the file.
    url: NotRequired[str]  # The URL to download the file.
    type: NotRequired[str]  # The MIME type of the file.
    size: NotRequired[int]  # The size of the file in bytes.

class FileFeature(TypedDict):
    files: NotRequired[list[FeatureFile]]  # List of downloadable files.

class License(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # A string representing the object's type. Objects of the same type share the same value.
    product_id: NotRequired[str]  # The ID of the product this license belongs to.
    status: NotRequired[LicenseStatus]
    key: NotRequired[str]  # The license key.
    activation: NotRequired[int]  # The number of instances that this license key was activated.
    activation_limit: NotRequired[int]  # The activation limit. Null if activations are unlimited.
    expires_at: NotRequired[str]  # The date the license key expires. Null if it does not have an expiration date.
    created_at: NotRequired[str]  # The creation date of the license key.
    instance: NotRequired[LicenseInstance]  # Associated license instances.

class LicenseInstance(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # A string representing the object’s type. Objects of the same type share the same value.
    name: NotRequired[str]  # The name of the license instance.
    status: NotRequired[LicenseInstanceStatus]  # The status of the license instance.
    created_at: NotRequired[str]  # The creation date of the license instance.

# The status of the license instance.
LicenseInstanceStatus = Literal['active', 'deactivated']

class LicenseInstanceList(TypedDict):
    items: NotRequired[list[LicenseInstance]]  # List of license instance items
    pagination: NotRequired[Pagination]  # Pagination details for the list

class LicenseList(TypedDict):
    items: NotRequired[list[License]]  # List of license items
    pagination: NotRequired[Pagination]  # Pagination details for the list

class Order(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # String representing the object's type. Objects of the same type share the same value.
    customer: NotRequired[str]  # The customer who placed the order.
    product: NotRequired[str]  # The product associated with the order.
    transaction: NotRequired[str]  # The transaction ID of the order
    discount: NotRequired[str]  # The discount ID of the order
    amount: NotRequired[int]  # The total amount of the order in cents. 1000 = $10.00
    sub_total: NotRequired[int]  # The subtotal of the order in cents. 1000 = $10.00
    tax_amount: NotRequired[int]  # The tax amount of the order in cents. 1000 = $10.00
    discount_amount: NotRequired[int]  # The discount amount of the order in cents. 1000 = $10.00
    amount_due: NotRequired[int]  # The amount due for the order in cents. 1000 = $10.00
    amount_paid: NotRequired[int]  # The amount paid for the order in cents. 1000 = $10.00
    currency: NotRequired[str]  # Three-letter ISO currency code, in uppercase. Must be a supported currency.
    fx_amount: NotRequired[int]  # The amount in the foreign currency, if applicable.
    fx_currency: NotRequired[str]  # Three-letter ISO code of the foreign currency, if applicable.
    fx_rate: NotRequired[float]  # The exchange rate used for converting between currencies, if applicable.
    status: NotRequired[OrderStatus]
    type: NotRequired[OrderType]
    affiliate: NotRequired[str]  # The affiliate associated with the order, if applicable.
    created_at: NotRequired[str]  # Creation date of the order
    updated_at: NotRequired[str]  # Last updated date of the order

class OrderList(TypedDict):
    items: NotRequired[list[Order]]  # List of order items
    pagination: NotRequired[Pagination]  # Pagination details for the list

class Pagination(TypedDict):
    total_records: NotRequired[int]  # Total number of records in the list
    total_pages: NotRequired[int]  # Total number of pages available
    current_page: NotRequired[int]  # The current page number
    next_page: NotRequired[int]  # The next page number, or null if there is no next page
    prev_page: NotRequired[int]  # The previous page number, or null if there is no previous page

class Product(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # String representing the object's type. Objects of the same type share the same value.
    name: NotRequired[str]  # The name of the product
    description: NotRequired[str]  # A brief description of the product
    image_url: NotRequired[str]  # URL of the product image. Only png as jpg are supported
    image_urls: NotRequired[list[str]]  # Ordered list of product image URLs. The first entry is the cover image (mirrored in image_url).
    features: NotRequired[list[Feature]]  # Features of the product.
    price: NotRequired[int]  # The price of the product in cents. 1000 = $10.00
    currency: NotRequired[str]  # Three-letter ISO currency code, in uppercase. Must be a supported currency.
    billing_type: NotRequired[ProductBillingType]
    billing_period: NotRequired[ProductBillingPeriod]
    status: NotRequired[ProductStatus]
    tax_mode: NotRequired[TaxMode]
    tax_category: NotRequired[TaxCategory]
    product_url: NotRequired[str]  # The product page you can redirect your customers to for express checkout.
    default_success_url: NotRequired[str]  # The URL to which the user will be redirected after successfull payment.
    custom_fields: NotRequired[list[CustomField]]  # Custom fields configured for the product. Collect additional information from your customer during checkout.
    created_at: NotRequired[str]  # Creation date of the product
    updated_at: NotRequired[str]  # Last updated date of the product

class ProductFeature(TypedDict):
    id: NotRequired[str]  # Unique identifier for the feature.
    description: NotRequired[str]  # A brief description of the feature.
    type: NotRequired[ProductFeatureType]
    private_note: NotRequired[str]  # Private note from the seller. This is only visible to the customer after purchase.
    file: NotRequired[FileFeature]  # File feature data containing downloadable files.
    license_key: NotRequired[License]  # License key issued for the order.
    customer_credits: NotRequired[CustomerCreditsFeature]  # Customer credits feature data.
    license: NotRequired[License]  # DEPRECATED: Use `license_key` instead. License key issued for the order.

class ProductList(TypedDict):
    items: NotRequired[list[Product]]  # List of product items
    pagination: NotRequired[Pagination]  # Pagination details for the list

class Refund(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # String representing the object’s type. Objects of the same type share the same value.
    status: NotRequired[RefundStatus]
    refund_amount: NotRequired[int]  # The refunded amount in cents. 1000 = $10.00
    refund_currency: NotRequired[str]  # Three-letter ISO currency code, in uppercase. Must be a supported currency.
    reason: NotRequired[RefundReason]
    transaction: NotRequired[Transaction]  # The transaction associated with the refund.
    checkout: NotRequired[str | Checkout]  # The checkout associated with the refund.
    order: NotRequired[str | Order]  # The order associated with the refund.
    subscription: NotRequired[str | Subscription]  # The subscription associated with the refund.
    customer: NotRequired[str | Customer]  # The customer associated with the refund.
    created_at: NotRequired[int]  # Creation date of the order as timestamp

class RefundResult(TypedDict):
    status: NotRequired[RefundStatus]

class CreditsReverseParams(TypedDict):
    transaction_id: Required[str]  # ID of the transaction to reverse

class ModerationScreenParams(TypedDict):
    prompt: Required[str]  # The text prompt to evaluate against content policies.
    external_id: NotRequired[str]  # An optional identifier to associate this request with.

class ModerationResult(TypedDict):
    id: NotRequired[str]  # Unique identifier for the moderation result.
    object: NotRequired[str]  # Object type.
    prompt: NotRequired[str]  # The prompt that was screened.
    external_id: NotRequired[str]  # The external identifier provided in the request.
    decision: NotRequired[ModerationResultDecision]  # The moderation decision.
    usage: NotRequired[Usage]  # Usage information for this call.

# The moderation decision.
ModerationResultDecision = Literal['allow', 'deny', 'flag']

class StatsPeriod(TypedDict):
    timestamp: NotRequired[int]  # Start of the period as a Unix timestamp in milliseconds (e.g. Monday of that week for weekly intervals)
    grossRevenue: NotRequired[int]  # Gross revenue in cents for this period
    netRevenue: NotRequired[int]  # Net revenue in cents for this period (after fees and taxes)

class StatsTotals(TypedDict):
    totalProducts: NotRequired[int]  # Total number of products in the store
    totalSubscriptions: NotRequired[int]  # Total number of subscriptions within the queried date range
    totalCustomers: NotRequired[int]  # Total number of customers within the queried date range
    totalPayments: NotRequired[int]  # Total number of payments within the queried date range
    activeSubscriptions: NotRequired[int]  # Number of currently active subscriptions
    totalRevenue: NotRequired[int]  # Total gross revenue in cents within the queried date range
    totalNetRevenue: NotRequired[int]  # Total net revenue in cents within the queried date range (after fees and taxes)
    netMonthlyRecurringRevenue: NotRequired[int]  # Net monthly recurring revenue in cents (after estimated fees)
    monthlyRecurringRevenue: NotRequired[int]  # Gross monthly recurring revenue in cents

class StatsSummary(TypedDict):
    totals: NotRequired[StatsTotals]  # Aggregated totals for the queried date range
    periods: NotRequired[list[StatsPeriod]]  # Time-series data points grouped by the requested interval. Only present when interval, startDate, and endDate are provided.

class Subscription(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # String representing the object's type. Objects of the same type share the same value.
    product: NotRequired[Product | str]  # The product associated with the subscription.
    customer: NotRequired[Customer | str]  # The customer who owns the subscription.
    items: NotRequired[list[SubscriptionItem]]  # Subscription items.
    collection_method: NotRequired[SubscriptionCollectionMethod]
    status: NotRequired[SubscriptionStatus]
    last_transaction_id: NotRequired[str]  # The ID of the last paid transaction.
    last_transaction: NotRequired[Transaction]  # The last paid transaction.
    last_transaction_date: NotRequired[str]  # The date of the last paid transaction.
    next_transaction_date: NotRequired[str]  # The date when the next subscription transaction will be charged.
    current_period_start_date: NotRequired[str]  # The start date of the current subscription period.
    current_period_end_date: NotRequired[str]  # The end date of the current subscription period.
    canceled_at: NotRequired[str]  # The date and time when the subscription was canceled, if applicable.
    created_at: NotRequired[str]  # The date and time when the subscription was created.
    updated_at: NotRequired[str]  # The date and time when the subscription was last updated.
    discount: NotRequired[SubscriptionDiscount]  # The discount applied to the subscription, if any.
    metadata: NotRequired[dict[str, Any]]  # Metadata for the subscription in the form of key-value pairs.

class SubscriptionDiscount(TypedDict):
    """The discount applied to the subscription, if any."""
    id: NotRequired[str]
    discountCode: NotRequired[str]
    name: NotRequired[str]
    type: NotRequired[SubscriptionDiscountType]
    amount: NotRequired[int]
    duration: NotRequired[SubscriptionDiscountDuration]
    durationInMonths: NotRequired[int]

SubscriptionDiscountType = Literal['percentage', 'fixed']

SubscriptionDiscountDuration = Literal['forever', 'once', 'repeating']

class SubscriptionItem(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # String representing the object’s type. Objects of the same type share the same value.
    product_id: NotRequired[str]  # The ID of the product associated with the subscription item.
    price_id: NotRequired[str]  # The ID of the price associated with the subscription item.
    units: NotRequired[int]  # The number of units for the subscription item.

class SubscriptionList(TypedDict):
    items: NotRequired[list[Subscription]]  # List of subscription items
    pagination: NotRequired[Pagination]  # Pagination details for the list

class CustomFieldText(TypedDict):
    max_length: NotRequired[int]  # Maximum character length constraint for the input.
    minimum_length: NotRequired[int]  # Minimum character length requirement for the input.
    value: NotRequired[str]  # The value of the input.

class CustomFieldTextConfig(TypedDict):
    max_length: NotRequired[int]  # Maximum character length constraint for the input.
    min_length: NotRequired[int]  # Minimum character length requirement for the input.

class Transaction(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # String representing the object's type. Objects of the same type share the same value.
    amount: NotRequired[int]  # The transaction amount in cents. 1000 = $10.00
    amount_paid: NotRequired[int]  # The amount the customer paid in cents. 1000 = $10.00
    discount_amount: NotRequired[int]  # The discount amount in cents. 1000 = $10.00
    currency: NotRequired[str]  # Three-letter ISO currency code, in uppercase. Must be a supported currency.
    type: NotRequired[TransactionType]
    tax_country: NotRequired[str]  # The ISO alpha-2 country code where tax is collected.
    tax_amount: NotRequired[int]  # The sale tax amount in cents. 1000 = $10.00
    status: NotRequired[TransactionStatus]
    refunded_amount: NotRequired[int]  # The amount that has been refunded in cents. 1000 = $10.00
    order: NotRequired[str]  # The order associated with the transaction.
    subscription: NotRequired[str]  # The subscription associated with the transaction.
    customer: NotRequired[str]  # The customer associated with the transaction.
    description: NotRequired[str]  # The description of the transaction.
    period_start: NotRequired[int]  # Start period for the invoice as timestamp
    period_end: NotRequired[int]  # End period for the invoice as timestamp
    created_at: NotRequired[int]  # Creation date of the order as timestamp

class TransactionList(TypedDict):
    items: NotRequired[list[Transaction]]  # List of transactions items
    pagination: NotRequired[Pagination]  # Pagination details for the list

class CreditsTransaction(TypedDict):
    id: NotRequired[str]  # Transaction ID
    store_id: NotRequired[str]  # Store ID
    reference: NotRequired[str]  # Reference string
    idempotency_key: NotRequired[str]  # Idempotency key
    reversal_of: NotRequired[str]  # ID of the transaction this reverses, if applicable
    entries: NotRequired[list[CreditsEntry]]  # Transaction entries
    created_at: NotRequired[str]  # Creation timestamp

class CustomerUpdateParams(TypedDict):
    customer_id: Required[str]  # The ID of the customer to update.
    name: NotRequired[str]  # The full name of the customer.
    metadata: NotRequired[dict[str, Any]]  # Additional metadata for the customer.

class ProductUpdateParams(TypedDict):
    name: NotRequired[str]  # Name of the product
    description: NotRequired[str]  # Description of the product
    image_url: NotRequired[str]  # URL of the product image
    image_urls: NotRequired[list[str]]  # Ordered list of product image URLs (max 8). The first entry is the cover image; when provided it takes precedence over image_url. An empty list removes all images.
    default_success_url: NotRequired[str]  # Redirect URL after successful payment.
    price: NotRequired[int]  # The price of the product in cents. Must be 0 (free product) or at least 100 (one whole unit of the currency).
    currency: NotRequired[ProductCurrency]
    billing_type: NotRequired[ProductRequestBillingType]
    billing_period: NotRequired[ProductRequestBillingPeriod]
    tax_mode: NotRequired[TaxMode]
    pay_what_you_want: NotRequired[bool]  # Enable pay-what-you-want pricing (one-time only).
    suggested_price: NotRequired[int]  # Suggested amount in cents when pay_what_you_want is enabled.

class SubscriptionUpdateParams(TypedDict):
    items: NotRequired[list[SubscriptionItemUpsert]]  # List of subscription items to update/create. If no item ID is provided, the item will be created.
    update_behavior: NotRequired[SubscriptionUpdateParamsUpdateBehavior]  # The update behavior for the subscription (defaults to proration)

# The update behavior for the subscription (defaults to proration)
SubscriptionUpdateParamsUpdateBehavior = Literal['proration-charge-immediately', 'proration-charge', 'proration-none']

class SubscriptionUpgradeParams(TypedDict):
    product_id: Required[str]  # The ID of the product to upgrade to
    update_behavior: NotRequired[SubscriptionUpgradeParamsUpdateBehavior]  # The update behavior for the subscription (defaults to proration-charge-immediately)

# The update behavior for the subscription (defaults to proration-charge-immediately)
SubscriptionUpgradeParamsUpdateBehavior = Literal['proration-charge-immediately', 'proration-charge', 'proration-none']

class SubscriptionItemUpsert(TypedDict):
    id: NotRequired[str]  # The id of the item to update.
    product_id: NotRequired[str]  # The ID of the product associated with the subscription item.
    price_id: NotRequired[str]  # The ID of the price associated with the subscription item.
    units: NotRequired[int]  # The number of units for the subscription item.

class Usage(TypedDict):
    units: NotRequired[int]  # Number of units consumed by this call.

class LicenseValidateParams(TypedDict):
    key: Required[str]  # The license key to validate.
    instance_id: Required[str]  # Id of the instance to validate.

class CheckoutCompletedEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[CheckoutCompletedEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[Checkout]  # Object related to the event.

# The event name.
CheckoutCompletedEventEventType = Literal['checkout.completed']

class DisputeCreatedEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[DisputeCreatedEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[Dispute]  # Object related to the event.

# The event name.
DisputeCreatedEventEventType = Literal['dispute.created']

class WebhookEvent(TypedDict):
    ...

class RefundCreatedEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[RefundCreatedEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[Refund]  # Object related to the event.

# The event name.
RefundCreatedEventEventType = Literal['refund.created']

class SubscriptionActiveEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[SubscriptionActiveEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[WebhookSubscription]  # Object related to the event.

# The event name.
SubscriptionActiveEventEventType = Literal['subscription.active']

class SubscriptionCanceledEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[SubscriptionCanceledEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[WebhookSubscription]  # Object related to the event.

# The event name.
SubscriptionCanceledEventEventType = Literal['subscription.canceled']

class WebhookSubscription(TypedDict):
    id: NotRequired[str]  # Unique identifier for the object.
    mode: NotRequired[EnvironmentMode]
    object: NotRequired[str]  # String representing the object's type. Objects of the same type share the same value.
    product: NotRequired[Product]  # The product associated with the subscription.
    customer: NotRequired[Customer]  # The customer who owns the subscription.
    items: NotRequired[list[SubscriptionItem]]  # Subscription items.
    collection_method: NotRequired[SubscriptionCollectionMethod]
    status: NotRequired[SubscriptionStatus]
    last_transaction_id: NotRequired[str]  # The ID of the last paid transaction.
    last_transaction: NotRequired[Transaction]  # The last paid transaction.
    last_transaction_date: NotRequired[str]  # The date of the last paid transaction.
    next_transaction_date: NotRequired[str]  # The date when the next subscription transaction will be charged.
    current_period_start_date: NotRequired[str]  # The start date of the current subscription period.
    current_period_end_date: NotRequired[str]  # The end date of the current subscription period.
    canceled_at: NotRequired[str]  # The date and time when the subscription was canceled, if applicable.
    created_at: NotRequired[str]  # The date and time when the subscription was created.
    updated_at: NotRequired[str]  # The date and time when the subscription was last updated.
    discount: NotRequired[WebhookSubscriptionDiscount]  # The discount applied to the subscription, if any.
    metadata: NotRequired[dict[str, Any]]  # Metadata for the subscription in the form of key-value pairs.

class WebhookSubscriptionDiscount(TypedDict):
    """The discount applied to the subscription, if any."""
    id: NotRequired[str]
    discountCode: NotRequired[str]
    name: NotRequired[str]
    type: NotRequired[WebhookSubscriptionDiscountType]
    amount: NotRequired[int]
    duration: NotRequired[WebhookSubscriptionDiscountDuration]
    durationInMonths: NotRequired[int]

WebhookSubscriptionDiscountType = Literal['percentage', 'fixed']

WebhookSubscriptionDiscountDuration = Literal['forever', 'once', 'repeating']

class SubscriptionExpiredEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[SubscriptionExpiredEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[WebhookSubscription]  # Object related to the event.

# The event name.
SubscriptionExpiredEventEventType = Literal['subscription.expired']

class WebhookSubscriptionPaidEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[WebhookSubscriptionPaidEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[WebhookSubscription]  # Object related to the event.

# The event name.
WebhookSubscriptionPaidEventEventType = Literal['subscription.paid']

class SubscriptionPastDueEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[SubscriptionPastDueEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[WebhookSubscription]  # Object related to the event.

# The event name.
SubscriptionPastDueEventEventType = Literal['subscription.past_due']

class SubscriptionPausedEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[SubscriptionPausedEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[WebhookSubscription]  # Object related to the event.

# The event name.
SubscriptionPausedEventEventType = Literal['subscription.paused']

class SubscriptionScheduledCancelEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[SubscriptionScheduledCancelEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[WebhookSubscription]  # Object related to the event.

# The event name.
SubscriptionScheduledCancelEventEventType = Literal['subscription.scheduled_cancel']

class SubscriptionTrialingEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[SubscriptionTrialingEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[WebhookSubscription]  # Object related to the event.

# The event name.
SubscriptionTrialingEventEventType = Literal['subscription.trialing']

class SubscriptionUnpaidEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[SubscriptionUnpaidEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[WebhookSubscription]  # Object related to the event.

# The event name.
SubscriptionUnpaidEventEventType = Literal['subscription.unpaid']

class SubscriptionUpdateEvent(TypedDict):
    id: NotRequired[str]  # Unique identifier for the event.
    eventType: NotRequired[SubscriptionUpdateEventEventType]  # The event name.
    created_at: NotRequired[int]  # Creation date of the event.
    object: NotRequired[WebhookSubscription]  # Object related to the event.

# The event name.
SubscriptionUpdateEventEventType = Literal['subscription.update']

